import Testing
@testable import DiaryCompanionCore

@Test func reminderAssistantPromptDescribesConfirmationEnvelopeContract() {
    let instruction = ReminderAssistantPrompt.systemInstruction

    #expect(instruction.contains("时间或周期信息不完整"))
    #expect(instruction.contains("先追问"))
    #expect(instruction.contains("仅输出一次"))
    #expect(instruction.contains(ReminderProposalEnvelopeParser.startMarker))
    #expect(instruction.contains(ReminderProposalEnvelopeParser.endMarker))
    #expect(instruction.contains("envelope 外"))
    #expect(instruction.contains("title"))
    #expect(instruction.contains("notes"))
    #expect(instruction.contains("start"))
    #expect(instruction.contains("durationMinutes"))
    #expect(instruction.contains("recurrence"))
    #expect(instruction.contains("schedulingMode"))
    #expect(instruction.contains("searchWindow"))
    #expect(instruction.contains("notificationEnabled"))
    #expect(instruction.contains("calendarEnabled"))
    #expect(instruction.contains("ISO8601"))
    #expect(instruction.contains("时区"))
    #expect(instruction.contains("fixed"))
    #expect(instruction.contains("findFreeTime"))
    #expect(instruction.contains("自动排期"))
    #expect(instruction.contains("用户确认前"))
    #expect(instruction.contains("不得声称已创建通知或日历"))
    #expect(instruction.contains("等待卡片确认"))
    #expect(instruction.contains(#"{"kind":"once"}"#))
    #expect(instruction.contains(#"{"kind":"daily","interval":Int,"end":End | null}"#))
    #expect(instruction.contains(#"{"kind":"weekly","interval":Int,"weekdays":[Int],"end":End | null}"#))
    #expect(instruction.contains(#"{"kind":"monthly","interval":Int,"day":Int,"end":End | null}"#))
    #expect(instruction.contains(#"{"kind":"monthlyLastDay","interval":Int,"end":End | null}"#))
    #expect(instruction.contains(#"{"kind":"yearly","interval":Int,"month":Int,"day":Int,"end":End | null}"#))
    #expect(instruction.contains(#"{"kind":"date","date":ISO8601 String}"#))
    #expect(instruction.contains(#"{"kind":"occurrenceCount","occurrenceCount":Int}"#))
    #expect(instruction.contains("fixed 要求 start"))
    #expect(instruction.contains("findFreeTime 要求 searchWindow"))
}
